# Generated by Django 2.1.4 on 2018-12-07 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('To_do_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='time',
        ),
    ]
