# Generated by Django 2.1.4 on 2018-12-07 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('To_do_app', '0002_remove_list_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='activity',
            field=models.CharField(default='Empty Entry', max_length=200),
        ),
    ]
