# Generated by Django 2.1.4 on 2018-12-08 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('To_do_app', '0005_list_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='time',
        ),
    ]
